---
title: "jessica_scratch_work"
format: html
editor_options: 
  chunk_output_type: console
---

```{r}
#install.packages("rinat")
library(rinat)
```

```{r}
# get_inat_obs_project("st-olaf-natural-lands", type = "info", raw = FALSE)
# result <- get_inat_obs_project("st-olaf-natural-lands", type = "observations")
```

```{r}
# obs_clean <- result |>
#   select(observed_on, description, latitude, longitude, species_guess, user_id, created_at, updated_at, place_guess, num_identification_agreements, num_identification_disagreements, quality_grade, out_of_range, uri, captive)
```

```{r}
stolaf_inat <- read.csv("~/mini-proj-II/clean_inat_stolaf.csv")
```


```{r}
inat_observations <- function(location, species) { 
    raw_obs <- get_inat_obs_project(location, type = "observations")

  #Created a new data frame called "obs_clean" from the previous data frame "raw_obs" which contains our raw data of observations. 
    obs_clean <- raw_obs |>
  
  #Using the select() function, we selected specific columns we want to include in our new data frame "obs_clean."
    select(observed_on, description, latitude, longitude, species_guess, user_id, created_at, updated_at,    place_guess, num_identification_agreements, num_identification_disagreements, quality_grade, uri, captive) |>
  
#We used the mutate() function to modify specific columns. 
#The ymd() function converts date columns to follow this format:  year-month-day 
#For the "created_at" and "updated_at" columns, we used the str_extract() function to isolate just the dates before reformatting it to years-month-day. 
#The parse_number() function extracts numeric values from "latitude" and "longitude" columns. 
#Finally, the replace_na() function for the "species_guess" column to replace any "NAs" with "unknown."
  
  mutate(observed_on = ymd(observed_on),
         latitude = parse_number(latitude), 
         longitude = parse_number(longitude),
         created_at = ymd(str_extract(created_at, "\\d{4}-\\d{2}-\\d{2}")),
         updated_at = ymd(str_extract(updated_at, "\\d{4}-\\d{2}-\\d{2}")),
         species_guess = str_to_lower(replace_na(species_guess, "unknown")))|>
  
#Here, we used the rename() function to assign new names to specific columns. 
          rename(species = species_guess,
          location = place_guess, 
          quality = quality_grade,
          URL = uri,
          id_agreements = num_identification_agreements,
          id_disagreements = num_identification_disagreements) |>
      filter(species == {{species}})
    obs_clean
}

inat_observations(location = "st-olaf-natural-lands", species = "blue jay")
```

```{r}
library(tidyverse)
library(stringr)
library(rvest)
library(polite)
library(sf)
library(maps)
library(viridis)
library(leaflet)
library(htmltools)
```

```{r}
session <- bow("https://www.dnr.state.mn.us/invasives/terrestrialplants/index.html", force = TRUE)

in_plants <- scrape(session) |>
  html_nodes("ul") |>
  html_text()
test <- in_plants[c(15,16,17,18)]
```

```{r}
str_view(x1, "(.)(.)(..)\\2\\1")
test2 <- data.frame(test)
test3 <- test2 |>
  mutate(test = str_replace_all(test, "([a-z])([A-Z])", "\\1*\\2")) |>
  separate(col = test, sep = "\\*", into = as.character(1:30)) |>
  pivot_longer(cols = 1:30, names_to = "drop", values_to = "species") |>
  select(species) |>
  filter(!is.na(species))
```

```{r}
species <- c("European Starling",
"Mute Swan",
"Asian-Long horned beetle",
"Brown marmorated stink bug",
"Emerald ash borer",
"Spongy moth",
"Japanese beetle",
"Spotted lantern fly",
"Eurasian swine",
"Earthworms",
"Jumping worm")
animals <- data.frame(species)
```

```{r}
invasives <- rbind(test3, animals) |>
  mutate(native = "invasive",
         species = str_to_lower(species))
```

```{r}
test4 <- clean_inat_stolaf |>
  mutate(species_guess = str_to_lower(species_guess)) |>
  left_join(invasives, by = join_by(species_guess == species))
```
