---
title: "Flexdashboard "
output: flexdashboard::flex_dashboard
runtime: shiny
---

```{r global, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(AER)
library(tidyverse)
library(rinat)
library(dplyr)
library(lubridate)

library(readr)
inat_stolaf <- read_csv("~/mini-proj-II/inat_with_invasives.csv")
```

About
==========================

Column {data-width = 200}
-------------------------

**Introduction**

We are interested in seeing what species are frequently reported at St. Olaf College and getting an idea of their distribution. We’d like to get an idea of the biodiversity that can be found at St. Olaf as well as how students are interacting with it. We hope to answer the frequency of how often students encounter certain species in terms of location and month, as well as over the years. We are also interested in observing what species are the most commonly identified how many of those are native or invasive. 

Column {data-width = 200}
-------------------------
Observation Location
==========================

```{r, echo=FALSE, warning=FALSE}
unique_coords <- unique(inat_stolaf[c("latitude", "longitude")])

library(leaflet)  

leaflet() |>
  addTiles() |>
  setView(lng = mean(unique_coords$longitude), 
          lat = mean(unique_coords$latitude), 
          zoom = 13) |> 
  addCircleMarkers(data = unique_coords,
    lat = ~latitude, 
    lng = ~longitude, 
    popup = "Observation Location",  
    radius = 2,
    weight = 2,
    color = "purple", 
    fillColor = "purple")

```

Common Species
========================================
Column {data-width=300}
-------------------------------------

```{r, echo=FALSE, warning=FALSE}
top25 <- inat_stolaf |>
  drop_na(species_guess) |>
  count(species_guess, sort = TRUE) |>
  slice(1:25)

top25joined <- top25|>
  left_join(inat_stolaf, by = "species_guess") 

top25joined |>
  ggplot(aes(x = species_guess, fill = quality_grade)) +
  geom_bar(position = "stack") + 
  theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1),  
        panel.grid.minor = element_line(color = "grey90")) + 
    labs(title = "Frequency of species observed and identified",
       subtitle = "Based on Quality Grade",
       x = "Species",
       y = "Number of observations") +
  scale_fill_viridis_d(option = "mako")
```

Column {data-width=700}
-------------------------------------
```{r,echo=FALSE}
inputPanel(
  checkboxGroupInput("checkGroup", label = h3("Years"), 
    choices = list("2010", "2011","2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025"),
    selected = "2025"),
)

renderPlot({
  toptwentyfive <- inat_stolaf |>
  drop_na(species_guess) |>
  count(species_guess, sort = TRUE) |>
  slice(1:25)
  
    inat_stolaf2 <- inat_stolaf |>
    mutate(observed_on = ymd(observed_on),
           year = year(observed_on)) |> 

    inner_join(toptwentyfive, by = join_by(species_guess)) |>
    filter(year %in% as.numeric(input$checkGroup)) |>
    group_by(species_guess, year, .drop = FALSE) |>
    summarise(count = n())


  ggplot(inat_stolaf2, 
         aes(x = year, y = count, color = species_guess, group = species_guess)) +
  geom_point() +
  geom_line() +
  labs(x = "year",
       y = "Num. Observations",
       color = "Species") +
        theme(axis.text = element_text(size = 18)) +
        theme(axis.title = element_text(size = 20)) +
        theme(plot.title = element_text(size=22)) +
  scale_x_continuous(breaks = ~ axisTicks(., log = FALSE)) +
    theme_bw()
})
```


Invasive vs Native Species
========================================

Column {data-width = 200}
-------------------------
```{r, echo = FALSE, warning = FALSE}
invasives <- inat_stolaf |>
  filter(native == "invasive")
```

```{r, echo = FALSE, warning = FALSE}
invasives |>
  group_by(species_guess) |>
  summarise(count = n()) |>
  mutate(species_guess = fct_reorder(species_guess, count)) |>
  ggplot(aes(x = species_guess, y = count)) +
  geom_col() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),  
        panel.grid.minor = element_line(color = "grey90")) +
  labs(x = "Species", y = "Num. Observations")  +
    theme_bw()
```

Column {data-width = 200}
-------------------------

```{r, echo = FALSE, warning = FALSE}
inputPanel(
  radioButtons("radio", label = h3("y-axis"),
    choices = list("Num. Invasives" = "num_invasive", "Prop. Invasives" = "prop_invasive"), 
    selected = "Num. Invasives"),
)

renderPlot({
  inat_stolaf |>
  mutate(year_obs = year(observed_on)) |>
  group_by(year_obs) |>
  summarise(total = n(),
            num_invasive = sum(native=="invasive", na.rm = TRUE),
            prop_invasive = num_invasive/total) |>
  pivot_longer(c(num_invasive, prop_invasive), names_to = "type",
               values_to = "invasive_obs") |>
  filter(type == input$radio) |>
  ggplot(aes(x = year_obs, y = invasive_obs)) +
  geom_point() +
  labs(x = "Year", y = "Invasive Observations")  +
    theme_bw()
}, height = 500)
```

Seasonal Shifts
========================================

Column {data-width = 400}
-------------------------

```{r, echo=FALSE}
inputPanel(
  checkboxGroupInput("checkGroup", label = h3("Species"), 
    choices = list("bloodroot", "virginia waterleaf","black-capped chickadee", "jack-in-the-pulpit", "american toad", "sugar maple", "white-faced meadowhawk", "american crow", "common green darner", "downy woodpecker"),
    selected = "bloodroot"),
)

renderPlot({
  topten <- inat_stolaf |>
  drop_na(species_guess) |>
  count(species_guess, sort = TRUE) |>
  filter(species_guess != "dicots") |>
  slice(1:10) 

inat_stolaf |>
  filter(!is.na(observed_on)) |>
  mutate(season = ifelse(month(observed_on) %in% c(12, 1, 2), "Winter", 
                         ifelse(month(observed_on) %in% c(3,4,5), "Spring",
                                ifelse(month(observed_on) %in% c(6,7,8), "Summer", "Fall"))),
         season = fct_relevel(season, "Winter", "Spring", "Summer", "Fall")) |>
  inner_join(topten, by = join_by(species_guess)) |>
  filter(species_guess %in% input$checkGroup) |>
  group_by(species_guess, season, .drop = FALSE) |>
  summarise(count = n())|>
  ggplot(aes(x = season, y = count, color = species_guess, group = species_guess)) +
  geom_point() +
  geom_line() +
  labs(x = "Season",
       y = "Num. Observations",
       color = "Species")  +
    theme_bw()
}, height = 500)
```

Column {data-width = 400}
-------------------------

```{r, echo=FALSE}
inputPanel(
  selectInput("select", label = h3("Season"), 
    choices = list("Winter", "Spring", "Summer", "Fall"), 
    selected = "Winter")
)

renderPlot({
  inat_stolaf |>
  filter(!is.na(observed_on)) |>
  mutate(season = ifelse(month(observed_on) %in% c(12, 1, 2), "Winter", 
                         ifelse(month(observed_on) %in% c(3,4,5), "Spring",
                                ifelse(month(observed_on) %in% c(6,7,8), "Summer", "Fall"))),
         season = fct_relevel(season, "Winter", "Spring", "Summer", "Fall"),
         native = replace_na(native, "native"),
         year_obs = year(observed_on)) |>
  group_by(native, season, year_obs, .drop = FALSE) |>
  summarise(count = n()) |>
  filter(season == input$select) |>
  ggplot(aes(x = native, y = count)) +
  geom_boxplot()  +
    theme_bw()
}, height = 500)
```