---
title: "Mini Project III - Tial and Jessica"
format: pdf
editor_options: 
  chunk_output_type: console
---
```{r}
#load libraries for extracting inat data
library(tidyverse)
library(rinat)
```


```{r}
#extract raw data of all observations
raw_obs <- get_inat_obs_project("st-olaf-natural-lands", type = "observations")

#
obs_clean <- raw_obs |>
   select(observed_on, description, latitude, longitude, species_guess, user_id, created_at, updated_at, place_guess, num_identification_agreements, num_identification_disagreements, quality_grade, uri, captive) |>
  mutate(observed_on = ymd(observed_on),
         latitude = parse_number(latitude), 
         longitude = parse_number(longitude),
         created_at = ymd(str_extract(created_at, "\\d{4}-\\d{2}-\\d{2}")),
         updated_at = ymd(str_extract(updated_at, "\\d{4}-\\d{2}-\\d{2}")),
         species_guess = replace_na(species_guess, "unknown"))|>
          rename (species = species_guess,
          location = place_guess, 
          quality = quality_grade,
          URL = uri) 
```

```{r}
write_csv(obs_clean, "TJ_mini3")
```

variable description table
